name: element
services:
  nginx:
    container_name: element
    depends_on:
      synapse:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://127.0.0.1:80/config.json']
      timeout: 5s
    image: vectorim/element-web:v1.12.18
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./element-config.json
        target: /app/config.json
      # Element overwrites default.conf and fails when we make it read-only
      - type: bind
        source: /dev/null
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./server.conf
        target: /etc/nginx/conf.d/server.conf
    networks:
      nginx:
        ipv4_address: 10.5.0.2
  postgres:
    container_name: postgres
    image: postgres:14.23-trixie
    healthcheck:
      test: [
        'CMD',
        'pg_isready', '-q', '-t', '3'
      ]
      start_period: 5s
      interval: 10s
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - type: bind
        source: ./postgres/data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres/db.txt
      POSTGRES_USER_FILE: /run/secrets/postgres/user.txt
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres/password.txt
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    secrets:
      - source: postgres
        target: /run/secrets/postgres/
    networks:
      nginx:
        ipv4_address: 10.5.0.4
  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:v1.152.1
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./synapse
        target: /data
    networks:
      nginx:
        ipv4_address: 10.5.0.3
  tor:
    extends:
      file: ./onion-website/src/docker-compose.yml
      service: tor
    profiles:
      - production
    depends_on:
      nginx:
        condition: service_healthy
    healthcheck:
      # Makes sure the hidden service is reachable
      test: [
        'CMD-SHELL',
        'curl -s --socks4a 10.5.3.2:9050 "$(cat /var/lib/tor/website/hostname)" >/dev/null'
      ]
      interval: 10s
      timeout: 120s
      start_period: 20s
    volumes:
      - type: bind
        source: ./tor/torrc
        target: /etc/tor/torrc
      # Path defined by torrc
      - type: bind
        source: ./onion-website/src/tor/secrets/
        target: /var/lib/tor/website/
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      tor:
        ipv4_address: 10.5.3.2
      nginx:
  prometheus:
    container_name: prometheus
    profiles:
      - production
    image: prom/prometheus:v3-distroless
    restart: unless-stopped
    depends_on:
      synapse:
        condition: service_healthy
        required: false
    healthcheck:
      test: [
        "CMD",
        "promtool", "check", "healthy"
      ]
      timeout: 3s
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus
        target: /prometheus/
    networks:
      nginx:
        ipv4_address: 10.5.0.253
      metrics:
        ipv4_address: 10.6.0.2
  grafana:
    container_name: grafana
    profiles:
      - production
    image: grafana/grafana-oss:13.0.1-security-01
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_healthy
        required: false
    ports:
      - ':3000'
    # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
    environment:
      GF_SECURITY_ADMIN_USER: $$__file{/run/secrets/admin_user.txt}
      GF_SECURITY_ADMIN_PASSWORD: $$__file{/run/secrets/admin_pass.txt}
      GF_SECURITY_ADMIN_EMAIL: $$__file{/run/secrets/admin_email.txt}
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning/
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/synapse.json
      GF_ANALYTICS_REPORTING_ENABLED: false # Anonymous usage statistics
    volumes:
      - type: bind
        source: ./grafana/datasources.yml
        target: /etc/grafana/provisioning/datasources/datasources.yml
        read_only: true
      - type: bind
        source: ./grafana/synapse.json
        target: /etc/grafana/provisioning/dashboards/synapse.json
        read_only: true
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana/
    secrets:
      - source: grafana
        target: /run/secrets/
    networks:
      metrics:
        ipv4_address: 10.6.0.3
  nginx-debug:
    extends:
      file: ./onion-website/src/docker-compose.yml
      service: container-link
    container_name: nginx-debug
    profiles:
      - development
    depends_on:
      - nginx
    environment:
      - FORWARD_ADDR=10.5.0.2:80
    ports:
      - :80
    networks:
      nginx:
        ipv4_address: 10.5.0.254
secrets:
  postgres:
    file: ./postgres/config/
  grafana:
    file: ./grafana/secrets/
volumes:
  prometheus:
  grafana-storage:
networks:
  tor:
    ipam:
      config:
        - subnet: 10.5.3.0/24 # 10.5.3.*
          gateway: 10.5.3.1
  nginx:
    ipam:
      config:
        - subnet: 10.5.0.0/24 # 10.5.0.*
          gateway: 10.5.0.1
  metrics:
    ipam:
      config:
        - subnet: 10.6.0.0/24 # 10.6.0.*
          gateway: 10.6.0.1
