# See: https://element-hq.github.io/synapse/latest/metrics-howto.html

global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "synapse"
    metrics_path: "/_synapse/metrics"
    scheme: "http"
    static_configs:
      - targets: ["synapse:9000"]
