on:
  push:

env:
  DOCKER_COMPOSE_VERSION: v5.1.0

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
        with:
          version: ${{ env.DOCKER_COMPOSE_VERSION }}
      - name: Build Compose stack
        run: docker compose --profile production --profile development build
