on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: v5.0.2
      - name: Build Compose stack
        run: docker compose --profile production --profile development build
